### ISSUE TITLE
Cant set registered users?

### ISSUE THREAD

**Issue by wouterverduin** [orthanc-server/orthanc-setup-samples#5]
Hi all! I am aiming to setup a, as simple as possible, PACS node.

I need it to be ARM64 so found your repository. Great work!

However, I cant seem to set the ORTHANC_REGISTERED_USERS enviroment variable for some reason. Container boots just fine but the login remains orthanc/orthanc instead of my specified value. 
Probably i am missing something but have no clue what to adjust. Build from the simplest example in the repository.

Help is much appreciated!

For reference my docker-compose:

```
version: '3.8'

services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: pacs
    restart: unless-stopped
    ports:
      - "4242:4242"   # DICOM port
      - "8042:8042"    # HTTP port
    volumes:
      - ./orthanc_data:/var/lib/orthanc/db:Z
    environment:
      - ORTHANC_NAME=My Orthanc
      - ORTHANC_REGISTERED_USERS={"test":"test"}

volumes:
  orthanc-storage:

```
